;[PROCESSED BY CW.AWK]
                    #ListOff
                    #Uses     cw.inc
                    #ListOn

; this just a generic bare minimum, which can be used for own extensions

PTA                 equ       $0000               ; Ports and data direction
PORTA               equ       $0000
DDRA                equ       $0004

COPCTL              equ       $FFFF               ; COP control register
