;[PROCESSED BY CW.AWK]
                    #ListOff
                    #Uses     cw.inc
                    #ListOn

; this just a generic bare minimum, which can be used for own extensions

PTAD                equ       $0010               ; Port A
PTADD               equ       $0011               ; Port A data direction

SRS                 equ       $0200               ; System Reset Status register
